[package]
name = "hell_carg"
version = "0.1.0"
authors = ["KoChan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
url = "2.1.1"